### ISSUE TITLE
_aruco.cpython-35m-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by nezumitti** [lvsn/deeptracking#12]
I would like to do various experiments using this.
so, I definitely want to realize the implementation.

I get an error when I do the 'test_sensor.py'
```
Traceback (most recent call last):
  File "test_sensor.py", line 11, in <module>
    from deeptracking.detector.detector_aruco import ArucoDetector
  File "/home/toshi/deeptracking/deeptracking/detector/detector_aruco.py", line 5, in <module>
    import aruco
  File "/usr/local/lib/python3.5/dist-packages/aruco.py", line 28, in <module>
    _aruco = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/aruco.py", line 24, in swig_import_helper
    _mod = imp.load_module('_aruco', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.5/dist-packages/_aruco.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN5aruco14CvDrawingUtils10draw3dCubeERN2cv3MatERNS_6MarkerERKNS_16CameraParametersEb

```
python-aruco Installation succeeded.
I think it is okay to check the link.

```
$ ldd /usr/local/lib/python3.5/dist-packages/_aruco.cpython-35m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffc0b3e5000)
	libopencv_core.so.3.1 => /usr/local/lib/libopencv_core.so.3.1 (0x00007fd6cd6c4000)
	libaruco.so.3.0 => /usr/local/lib/libaruco.so.3.0 (0x00007fd6cd382000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd6cd000000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd6cccf7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd6ccae1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd6cc717000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd6cc4fd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd6cc2f9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd6cc0dc000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd6cbed4000)
	libopencv_calib3d.so.3.1 => /usr/local/lib/libopencv_calib3d.so.3.1 (0x00007fd6cbb62000)
	libopencv_ml.so.3.1 => /usr/local/lib/libopencv_ml.so.3.1 (0x00007fd6cb8a1000)
	libopencv_highgui.so.3.1 => /usr/local/lib/libopencv_highgui.so.3.1 (0x00007fd6cb694000)
	libopencv_imgproc.so.3.1 => /usr/local/lib/libopencv_imgproc.so.3.1 (0x00007fd6c9c51000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd6ce692000)
	libopencv_features2d.so.3.1 => /usr/local/lib/libopencv_features2d.so.3.1 (0x00007fd6c9987000)
	libopencv_flann.so.3.1 => /usr/local/lib/libopencv_flann.so.3.1 (0x00007fd6c972e000)
	libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007fd6c90e3000)
	libgdk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007fd6c8e2e000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fd6c8b1a000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007fd6c88f8000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fd6c86a5000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fd6c8394000)
	libopencv_imgcodecs.so.3.1 => /usr/local/lib/libopencv_imgcodecs.so.3.1 (0x00007fd6c7e32000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fd6c7c2e000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fd6c7a21000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fd6c76e7000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fd6c74e1000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007fd6c72bc000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fd6c6f34000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007fd6c6d1e000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007fd6c6ad2000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fd6c688f000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fd6c6685000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fd6c6482000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fd6c6272000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007fd6c6067000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fd6c5e5d000)
	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007fd6c5c5a000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fd6c5a57000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fd6c5845000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fd6c559d000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fd6c52f3000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fd6c50ce000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fd6c4eca000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fd6c4cc0000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fd6c4a9e000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fd6c4896000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fd6c4626000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fd6c43cd000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fd6c41ab000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fd6c3f90000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fd6c3d32000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007fd6c3b29000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fd6c3900000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fd6c36fc000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fd6c34f6000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fd6c32d0000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007fd6c30c8000)

```

What do you think is the problem?

**Comment by MathGaron** [comment]
Hey Nezumitti,

I am finishing up a deadline so I will have more time to help next week, meanwhile, as you already saw issue #6 might be similar. I indeed forgot to put information about Aruco installation. 

The installed setup on my side is :
https://github.com/fehlfarbe/python-aruco.git
with this commit : dbc29c5cdf98467cb987c565c62402f05066bb2b

I have not tested this code for a while but trying this might be a good direction. Else the code using aruco is quite straightforward as only a single class is calling 3-4 functions from the library, it might not be too hard to port to OpenCV's implementation for example.

**Comment by nezumitti** [comment]
Mr. MathGaron,
Thank you for your reply while you are busy.I challenged, but the same problem has occurred.Perhaps using python 3 may be a problem.I will review the environment once again.I may ask you again.
Thank you!

**Comment by nezumitti** [comment]
Mr. MathGaron,
According to [this](https://github.com/Myzhencai/deeptracking/wiki/ALL-DETAILS-OF-deeptracking-project.) site, Opencv 3.1 is used.
However, to build aruco 1.3.0 seems to require opencv 3.4, what is your opencv version?

**Comment by MathGaron** [comment]
I installed my setup with python3, although it is "experimental" I had not compatibility issues. My opencv version is 3.1.0.

Also newer version of the aruco wrapper might not work directly, I think that they changed the API since then. So you might have to either update the aruco calls or use the commit I provided.

**Comment by nezumitti** [comment]
Successfully implemented!
thank you
When is the tracker algorithm posting?
I am very much looking forward to it.

**Comment by MathGaron** [comment]
awesome! I actually just started working on it, you can expect it to be online before next Friday.
